# Generated by Django 4.0.5 on 2022-06-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=30)),
                ('data_criacao', models.DateField(default=None, null=True)),
                ('peso', models.CharField(max_length=5)),
                ('altura', models.CharField(max_length=5)),
                ('idade', models.CharField(max_length=3)),
            ],
        ),
    ]
