# Generated by Django 4.0.5 on 2022-06-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refeicao', models.CharField(max_length=500)),
                ('porcao', models.CharField(max_length=20)),
                ('horario', models.CharField(max_length=10)),
                ('tipo_refeicao', models.CharField(max_length=50)),
            ],
        ),
    ]
