# Generated by Django 4.0.5 on 2022-06-24 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_cardapio2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cardapio2',
            new_name='CardapioCliente',
        ),
        migrations.RenameModel(
            old_name='Cardapio',
            new_name='Usuario',
        ),
    ]
